// Package password hashes and verifies user passwords with PBKDF2-HMAC-SHA256
// from the standard library, so slock needs no cryptography dependency.
//
// PBKDF2 is a deliberate trade-off. It is the only password KDF in the Go
// standard library, and unlike bcrypt, scrypt or argon2 it is not memory-hard:
// an attacker with GPUs gets more leverage per dollar against it. The
// iteration count below follows the OWASP recommendation for PBKDF2-HMAC-SHA256
// and costs roughly 150ms per hash on a modern core, which keeps online
// guessing slow and offline cracking expensive, but a memory-hard KDF would be
// stronger. Revisit if password hashes ever leak.
package password

import (
	"crypto/pbkdf2"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"
	"strconv"
	"strings"
)

const (
	// algorithm is the prefix of every encoded hash, so the format can change
	// later without guessing what an existing value is.
	algorithm = "pbkdf2-sha256"

	// Iterations is the work factor. Raising it invalidates DummyHash, which
	// TestDummyHashMatchesParameters guards.
	Iterations = 600_000

	saltLen = 16
	keyLen  = 32
)

// ErrInvalidHash means a stored value is not something this package produced.
var ErrInvalidHash = errors.New("password: malformed hash")

var b64 = base64.RawStdEncoding

// Hash derives an encoded hash of plain, with a fresh random salt. The result
// is self-describing: "pbkdf2-sha256$<iterations>$<salt>$<key>".
func Hash(plain string) (string, error) {
	salt := make([]byte, saltLen)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}
	return hashWith(plain, salt, Iterations)
}

func hashWith(plain string, salt []byte, iter int) (string, error) {
	key, err := pbkdf2.Key(sha256.New, plain, salt, iter, keyLen)
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("%s$%d$%s$%s", algorithm, iter, b64.EncodeToString(salt), b64.EncodeToString(key)), nil
}

// Verify reports whether plain matches encoded. It always performs the full
// derivation described by encoded and compares in constant time. A malformed
// hash is a false, never a panic: a corrupt row must not let anyone in.
func Verify(encoded, plain string) bool {
	salt, want, iter, err := parse(encoded)
	if err != nil {
		return false
	}
	got, err := pbkdf2.Key(sha256.New, plain, salt, iter, len(want))
	if err != nil {
		return false
	}
	return subtle.ConstantTimeCompare(got, want) == 1
}

// parse splits an encoded hash into its parts.
func parse(encoded string) (salt, key []byte, iter int, err error) {
	parts := strings.Split(encoded, "$")
	if len(parts) != 4 || parts[0] != algorithm {
		return nil, nil, 0, ErrInvalidHash
	}
	iter, err = strconv.Atoi(parts[1])
	if err != nil || iter < 1 {
		return nil, nil, 0, ErrInvalidHash
	}
	if salt, err = b64.DecodeString(parts[2]); err != nil || len(salt) == 0 {
		return nil, nil, 0, ErrInvalidHash
	}
	if key, err = b64.DecodeString(parts[3]); err != nil || len(key) == 0 {
		return nil, nil, 0, ErrInvalidHash
	}
	return salt, key, iter, nil
}

// DummyHash is a real hash of a value nobody knows, used to spend the same
// work on a login for an address that has no account. It must carry the same
// parameters as Hash, or the timing it is there to hide would leak.
// Generated by hashing 32 random bytes; the plaintext was never recorded.
const DummyHash = "pbkdf2-sha256$600000$4wh0IQz4kOweMf0JOvf6/w$" +
	"AjkIpJlt46Qlx9I5D/lD790twovpgTI8IHX2AjvB/54"
